@startuml

package "Design Lab Bounded Context" {

    package "Domain Layer" {

        enum ProjectStatus {
            Blueprint
            Garment
            Template
        }

        enum GarmentGender {
            MEN
            WOMEN
            UNISEX
            KIDS
        }

        enum GarmentSize {
            XS
            S
            M
            L
            XL
            XXL
        }

        enum LayerType {
            IMAGE
            TEXT
        }

        enum GarmentColor {
            BLACK
            GRAY
            LIGHT_GRAY
            WHITE
            RED
            PINK
            LIGHT_PURPLE
            PURPLE
            LIGHT_BLUE
            CYAN
            SKY_BLUE
            BLUE
            GREEN
            LIGHT_GREEN
            YELLOW
            DARK_YELLOW

            ---
            EGarmentColor Value
            String ToHexCode()
        }

        class "Project" {
            ProjectId id
            UserId userId
            String title
            String previewImageUrl
            ProjectStatus status
            ProjectGender gender
            GarmentColor garmentColor
            GarmentSize size
            Date createdAt
            Date lastModifiedAt
            List<Layer> layers
        }

        abstract class "Layer" {
            LayerId id
            int x
            int y
            int z
            int opacity
            boolean isVisible
            LayerType type
            Date createdAt
            Date lastModifiedAt
        }

        class "ImageLayer" extends "Layer" {
            String imageUrl
            int width
            int height
        }

        class "TextLayer" extends "Layer" {
            String text
            int fontSize
            String fontColor
            String fontFamily
            boolean isBold
            boolean isItalic
            boolean isUnderlined
        }

        Project "1" *-- "0..*" Layer : contains >
    }
}
@enduml